### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by Alexanderallenbrown** [tr3buchet/truths#1]
Hi there. I'm trying to use pip (python3) to install your library on RHEL7. It installs cleanly, but then throws the following error on import:
`import truths`

yields:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brownaa/truths/truths/__init__.py", line 18, in <module>
    from truths import Truths
ImportError: cannot import name 'Truths'

Do you have any idea what's up with this? It happens whether I use pip3 to install or clone the repo and do python3 setup.py install.

**Comment by Alexanderallenbrown** [comment]
EDIT: I realize that this was written for python2.7, so I changed __init__.py to read
"from truths.truths import Truths" and changed the top line to read #!/usr/bin/python3 for my application. Thanks for writing this module... it's pretty cool.

**Comment by trinitronx** [comment]
Alternate fix that should allow for both versions:

```
import sys
if sys.version_info[0] < 3:
    from truths import Truths
else:
   from truths.truths import Truths
```
