### ISSUE TITLE
Cannot import name 'Truths' from partially initialized module 'truths'

### ISSUE THREAD

**Issue by juanzitelli** [tr3buchet/truths#8]
I'm trying to import this package but it doesn't seem to be working...

I've installed it globally, and despite the fact that the intepreter finds the package, it can't import it

This is the error I'm getting:

`Traceback (most recent call last):
  File "/home/juanzitelli/dev/Python/modularArithmetics/main.py", line 1, in <module>
    from truths import Truths
  File "/usr/local/lib/python3.8/dist-packages/truths/__init__.py", line 18, in <module>
    from truths import Truths
ImportError: cannot import name 'Truths' from partially initialized module 'truths' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/truths/__init__.py)`

and my code is just this snippet:

![image](https://user-images.githubusercontent.com/39205380/98824207-c9959700-2411-11eb-9bf1-71f5303b739a.png)

**Comment by p98a** [comment]
Is there any solution for this? Or may be some other way to get the truth table for any expression?

**Comment by PolSerg** [comment]
> 

need to fix `__init__.py` file
you need to add a dot in the only line of code, it should be like this:
`from .truths import Truths`
